# Generated by Django 2.2 on 2021-11-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookTitle', models.CharField(max_length=200)),
                ('bookCategory', models.CharField(max_length=200)),
                ('bookDescription', models.CharField(max_length=500)),
                ('bookRating', models.IntegerField()),
                ('bookImage', models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Question_Mark.svg/1200px-Question_Mark.svg.png', max_length=500)),
            ],
        ),
    ]
