# Generated by Django 2.2 on 2021-11-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='bookRating',
            field=models.FloatField(default=0),
        ),
    ]
