# Generated by Django 2.2 on 2021-11-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20211101_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='bookDescription',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
